#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update && sudo apt-get install nginx

sudo service nginx start

sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo nginx -t

service nginx restart
