#!/usr/bin/env bash
#configure web-02 to be identical to web-01

#install servers
apt-get -y update
apt-get -y install nginx

#Start nginx service
sudo service nginx start

#create index.html
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection
sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#create an error page
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/^}$/i \ \n\terror_page 404 /404.html;\n\n\tlocation /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

#test
sudo nginx -t

service nginx restart
