#!/usr/bin/env bash
#debugging skills - installation from listening on port 80
sudo apt-get update
sudo apt-get install -y nginx
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/defualt
sudo nginx -t
sudo service nginx restart
sudo ufw allow 'Nginx Full'
sudo ufw reload
