#!/usr/bin/env bash
#debugging skills - installation from listening on port 80
sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl enable nginx
sudo systemctl start nginx
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
sudo ufw allow 'Nginx Full'
sudo ufw reload
