#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using the while loop + IFS

file="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
echo "The user USERNAME is part of the $f4 gang,"\
"lives in HOME_DIRECTORY and rides $f7."\
"USER ID's place is protected by the passcode $f2,"\
"more info about the user here: $f5"
done < "$file"
