#!/usr/bin/env bash
#Bash script that displays Best School 10 times

count=0

while [ $count -lt 11 ]
do
	if [ $count = 4 ]
	then
		echo "bad luck"
	elif [ $count = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
